preset: laravel

enabled:
  - no_extra_consecutive_blank_lines
  - short_array_syntax
  - method_separation
  - phpdoc_indent
  - phpdoc_inline_tag
  - phpdoc_no_access
  - phpdoc_no_package
  - phpdoc_scalar
  - phpdoc_trim
  - phpdoc_type_to_var
  - phpdoc_types
  - phpdoc_var_without_name
  - blank_line_before_return
  - no_short_bool_cast
  - single_quote
  - space_after_semicolon
  - cast_spaces
  - standardize_not_equals
  - trim_array_spaces
  - unalign_equals
  - unneeded_control_parentheses
  - no_unused_imports
  - no_whitespace_in_blank_line
